const cards_catalog = [
    { id: "KD-001", nome: "Kind", tipo: "action", nivel: 5, atk: 3000, def: 2000, efeito: "Ato/Efeito: Seja Gentil com todos sem excessôes, seja paciente e legal com todos, pois você não sabe o que a pessoa esta passando e quais demonios ela esta enfrentando/ Gentileza: pode escolher uma carta de action do oponente e destrui-la", imagem: "images/kind.jpg" },
    { id: "KD-002", nome: "Kind", tipo: "action", nivel: 5, atk: 3000, def: 2000, efeito: "Ato/Efeito: Seja Gentil com todos sem excessôes, seja paciente e legal com todos, pois você não sabe o que a pessoa esta passando e quais demonios ela esta enfrentando/ Gentileza: pode escolher uma carta de action do oponente e destrui-la", imagem: "images/kind.jpg" },
    { id: "KD-003", nome: "Kind", tipo: "action", nivel: 5, atk: 3000, def: 2000, efeito: "Ato/Efeito: Seja Gentil com todos sem excessôes, seja paciente e legal com todos, pois você não sabe o que a pessoa esta passando e quais demonios ela esta enfrentando/ Gentileza: pode escolher uma carta de action do oponente e destrui-la", imagem: "images/kind.jpg" },
    { id: "KD-004", nome: "Kind", tipo: "action", nivel: 5, atk: 3000, def: 2000, efeito: "Ato/Efeito: Seja Gentil com todos sem excessôes, seja paciente e legal com todos, pois você não sabe o que a pessoa esta passando e quais demonios ela esta enfrentando/ Gentileza: Ato/Efeito: Seja Gentil com todos sem excessôes, seja paciente e legal com todos, pois você não sabe o que a pessoa esta passando e quais demonios ela esta enfrentando/ Gentileza: pode escolher uma carta de action do oponente e destrui-la", imagem: "images/kind.jpg" },
    { id: "KD-005", nome: "Kind", tipo: "action", nivel: 5, atk: 3000, def: 2000, efeito: "Ato/Efeito: Seja Gentil com todos sem excessôes, seja paciente e legal com todos, pois você não sabe o que a pessoa esta passando e quais demonios ela esta enfrentando/ Gentileza: pode escolher uma carta de action do oponente e destrui-la", imagem: "images/kind.jpg" },
    { id: "LT-001", nome:"Ouvinte", tipo:"action", nivel: 3, atk: 1500, def: 600, efeito: "Ato/Efeito: As vezes quando a pessoa esta estressada e responde com odio, é porque teve muita coisa guardada dentro dela que não foi espressada, guardando um rancor que só pode ser retidado ao ser escutado por alguem. [qual a ultima vez que voce se propos a ouvir o desabafo de alguem?]/ Escutar:reduz o dano do proximo ataque pela metade", imagem: "images/escutar.webp" },
    { id: "LT-002", nome:"Ouvinte", tipo:"action", nivel: 3, atk: 1500, def: 600, efeito: "Ato/Efeito: As vezes quando a pessoa esta estressada e responde com odio, é porque teve muita coisa guardada dentro dela que não foi espressada, guardando um rancor que só pode ser retidado ao ser escutado por alguem. [qual a ultima vez que voce se propos a ouvir o desabafo de alguem?]/ Escutar:reduz o dano do proximo ataque pela metade", imagem: "images/escutar.webp" },
    { id: "LT-003", nome:"Ouvinte", tipo:"action", nivel: 3, atk: 1500, def: 600, efeito: "Ato/Efeito: As vezes quando a pessoa esta estressada e responde com odio, é porque teve muita coisa guardada dentro dela que não foi espressada, guardando um rancor que só pode ser retidado ao ser escutado por alguem. [qual a ultima vez que voce se propos a ouvir o desabafo de alguem?]/ Escutar:reduz o dano do proximo ataque pela metade", imagem: "images/escutar.webp" },
    { id: "LT-004", nome:"Ouvinte", tipo:"action", nivel: 3, atk: 1500, def: 600, efeito: "Ato/Efeito: As vezes quando a pessoa esta estressada e responde com odio, é porque teve muita coisa guardada dentro dela que não foi espressada, guardando um rancor que só pode ser retidado ao ser escutado por alguem. [qual a ultima vez que voce se propos a ouvir o desabafo de alguem?]/ Escutar:reduz o dano do proximo ataque pela metade", imagem: "images/escutar.webp" },
    { id: "LT-005", nome:"Ouvinte", tipo:"action", nivel: 3, atk: 1500, def: 600, efeito: "Ato/Efeito: As vezes quando a pessoa esta estressada e responde com odio, é porque teve muita coisa guardada dentro dela que não foi espressada, guardando um rancor que só pode ser retidado ao ser escutado por alguem. [qual a ultima vez que voce se propos a ouvir o desabafo de alguem?]/ Escutar:reduz o dano do proximo ataque pela metade", imagem: "images/escutar.webp" },
    { id: "LT-006", nome:"Ouvinte", tipo:"action", nivel: 3, atk: 1500, def: 600, efeito: "Ato/Efeito: As vezes quando a pessoa esta estressada e responde com odio, é porque teve muita coisa guardada dentro dela que não foi espressada, guardando um rancor que só pode ser retidado ao ser escutado por alguem. [qual a ultima vez que voce se propos a ouvir o desabafo de alguem?]/ Escutar: reduz o dano do proximo ataque pela metade", imagem: "images/escutar.webp" },
    { id: "HG-001", nome:"abraço", tipo:"action", nivel: 4, atk: 2100, def:1200, efeito: "Ato: Quando você tem muitas aflições na vida, e o estresse começa a ficar maior a cada dia, um abraço pode aliviar as dores, como se compartilhase-mos a dor com o outro, [qual foi a ultima vez que voce abraçou alguem querido?]", imagem: "images/abraco.jpg"},
    { id: "HG-002", nome:"abraço", tipo:"action", nivel: 4, atk: 2100, def:1200, efeito: "Ato: Quando você tem muitas aflições na vida, e o estresse começa a ficar maior a cada dia, um abraço pode aliviar as dores, como se compartilhase-mos a dor com o outro, [qual foi a ultima vez que voce abraçou alguem querido?]", imagem: "images/abraco.jpg"},
    { id: "HG-003", nome:"abraço", tipo:"action", nivel: 4, atk: 2100, def:1200, efeito:"Ato: Quando você tem muitas aflições na vida, e o estresse começa a ficar maior a cada dia, um abraço pode aliviar as dores, como se compartilhase-mos a dor com o outro, [qual foi a ultima vez que voce abraçou alguem querido?]", imagem: "images/abraco.jpg"},
    { id: "HG-004", nome:"abraço", tipo:"action", nivel: 4, atk: 2100, def:1200, efeito:"Ato: Quando você tem muitas aflições na vida, e o estresse começa a ficar maior a cada dia, um abraço pode aliviar as dores, como se compartilhase-mos a dor com o outro, [qual foi a ultima vez que voce abraçou alguem querido?]", imagem: "images/abraco.jpg"},
    { id: "SN-001", nome: "Sonic The Hedgehog", tipo: "action", nivel: 5, atk: 3000, def: 2000, efeito: "História: A coisa mais Rapida Viva, um cara que ama aventuras e tem como mestre o vento que sopra livremente, ah e ele gosta de cachorro quente com chilli :D", imagem:"images/soniccard.jpg"},
    { id: "SN-002", nome: "Sonic The Hedgehog", tipo: "action", nivel: 5, atk: 3000, def: 2000, efeito: "História: A coisa mais Rapida Viva, um cara que ama aventuras e tem como mestre o vento que sopra livremente, ah e ele gosta de cachorro quente com chilli :D", imagem:"images/soniccard.jpg"},
    {id: "NR-001", nome: "Naruto Uzumaki", tipo: "action",  nivel: 5, atk: 2000, def:3000, efeito: "Historia: Menosprezado por todos sem saber o motivo, esse garoto com determinação de ferro tem o sonho de se tornar Hokage e provar pra todos que até um fracassado pode mudar seu destino e se tornar o mais forte! ", imagem: "images/narutocard.jpg"},
    {id: "NR-002", nome: "Naruto Uzumaki", tipo: "action",  nivel: 5, atk: 2000, def:3000, efeito: "Historia: Menosprezado por todos sem saber o motivo, esse garoto com determinação de ferro tem o sonho de se tornar Hokage e provar pra todos que até um fracassado pode mudar seu destino e se tornar o mais forte! ", imagem: "images/narutocard.jpg"},
    {id: "SM-001", nome: "Homem-Aranha", tipo: "action",  nivel: 5, atk:2500, def:1500, efeito: "Historia: Picado por uma aranha radioativa, o garoto Peter Parker ganhou poderes de aranha! Porem por uma decisão ruim, seu tio Ben morre pelo bandito que Peter deixou escapar, fazendo o garoto entender que Com Grandes Poderes Vem Grandes Responsabilidades/Sentido Aranha: ative o efeito negando um ataque do oponente pelo custo de 500 de atk",imagem: "images/aranha.webp" },
    {id: "SM-001", nome: "Homem-Aranha", tipo: "action",  nivel: 5, atk:2500, def:1500, efeito: "Historia: Picado por uma aranha radioativa, o garoto Peter Parker ganhou poderes de aranha! Porem por uma decisão ruim, seu tio Ben morre pelo bandito que Peter deixou escapar, fazendo o garoto entender que Com Grandes Poderes Vem Grandes Responsabilidades/Sentido Aranha: ative o efeito negando um ataque do oponente pelo custo de 500 de atk",imagem: "images/aranha.webp" },
    {id: "SM-001", nome: "Homem-Aranha", tipo: "action",  nivel: 5, atk:2500, def:1500, efeito: "Historia: Picado por uma aranha radioativa, o garoto Peter Parker ganhou poderes de aranha! Porem por uma decisão ruim, seu tio Ben morre pelo bandito que Peter deixou escapar, fazendo o garoto entender que Com Grandes Poderes Vem Grandes Responsabilidades/Sentido Aranha: ative o efeito negando um ataque do oponente pelo custo de 500 de atk",imagem: "images/aranha.webp" },
    {id: "VD-001", nome: "Vida", tipo: "action",  nivel: 7, atk:490, def:490, efeito:"Efeito: Caso essa carta seja reunida com (Verdade, Caminho, Luz, Verbo) o jogador ganha a partida automaticamente", imagem: "images/Vida.jpg"},
    {id:"VD-002", nome:"Verdade", tipo: "action", nivel: 7,atk:490, def:490, efeito:"Efeito: Caso essa carta seja reunida com (Vida, Caminho, Luz, Verbo) o jogador ganha a partida automaticamente", imagem: "images/Verdade.jpg"},
    {id: "CA-001", nome: "Caminho", tipo: "action", nivel: 7, atk:490, def:490, efeito:"Efeito: Caso essa carta seja reunida com (Vida, Verdade, Luz, Verbo) o jogador ganha a partida automaticamente", imagem: "images/Caminho.jpg"},
    {id: "LZ-001", nome: "Luz",  tipo: "action",  nivel: 7, atk:490, def:490, efeito:"Efeito: Caso essa carta seja reunida com (Caminha, Verdade, Vida, Verbo) o jogador ganha a partida automaticamente", imagem: "images/Luz.jpg"},
    {id: "VB-001", nome: "Luz",  tipo: "action",  nivel: 7, atk:490, def:490, efeito:"Efeito: Caso essa carta seja reunida com (Caminha, Verdade, Vida, Luz) o jogador ganha a partida automaticamente", imagem: "images/Verbo.jpg"},
    { id: "AC-001", nome: "Aceitação", tipo: "pensamentos", efeito: "Aceitação: nega um ataque inimigo", imagem: "images/aceitacao.webp" },
    { id: "AC-002", nome: "Aceitação", tipo: "pensamentos", efeito: "Aceitação: nega um ataque inimigo", imagem: "images/aceitacao.webp" },
    { id: "AC-003", nome: "Aceitação", tipo: "pensamentos", efeito: "Aceitação: nega um ataque inimigo", imagem: "images/aceitacao.webp" },
    { id: "AC-004", nome: "Aceitação", tipo: "pensamentos", efeito: "Aceitação: nega um ataque inimigo", imagem: "images/aceitacao.webp" },
    { id: "AC-005", nome: "Aceitação", tipo: "pensamentos", efeito: "Aceitação: nega um ataque inimigo", imagem: "images/aceitacao.webp" },
    { id: "DS-001", nome: "Descanso", tipo: "pensamentos", efeito: "Cochilinho bom: recupera 1000 LP", imagem: "images/descanso.jpg"},
    { id: "DS-002", nome: "Descanso", tipo: "pensamentos", efeito: "Cochilinho bom: recupera 1000 LP", imagem: "images/descanso.jpg"},
    { id: "DS-003", nome: "Descanso", tipo: "pensamentos", efeito: "Cochilinho bom: recupera 1000 LP", imagem: "images/descanso.jpg"},
    { id: "DS-004", nome: "Descanso", tipo: "pensamentos", efeito: "Cochilinho bom: recupera 1000 LP", imagem: "images/descanso.jpg"},
    { id: "CM-001", nome: "calma", tipo: "pensamentos", efeito: "Mantendo a Calma e pensando melhor: puxa uma carta do seu deck", imagem:"images/calma.jpg"},
    { id: "CM-002", nome: "calma", tipo: "pensamentos", efeito: "Mantendo a Calma e pensando melhor: puxa uma carta do seu deck", imagem:"images/calma.jpg"},
    { id: "CM-003", nome: "calma", tipo: "pensamentos", efeito: "Mantendo a Calma e pensando melhor: puxa uma carta do seu deck", imagem:"images/calma.jpg"},
    {id: "YG-001", nome: "Yami Yugi", nivel: 4, tipo: "action", atk: 2500, def: 2100, efeito: "Historia/Efeito: O melhor duelista de YU-GI-OH! quando Yugi Moto resolve o enigma do milênio ele invoca o espirito do farao! só que por ser um shonen ele sabe como usar o 'poder do protagonista' né :]/ ROUBE 100 LP do seu oponente para voce xdxd", imagem:"images/YUGI.jpg"},
    {id: "YG-001", nome: "Yami Yugi", nivel: 4, tipo: "action", atk: 2500, def: 2100, efeito: "Historia/Efeito: O melhor duelista de YU-GI-OH! quando Yugi Moto resolve o enigma do milênio ele invoca o espirito do farao! só que por ser um shonen ele sabe como usar o 'poder do protagonista' né :]/ ROUBE 100 LP do seu oponente para voce xdxd", imagem:"images/YUGI.jpg"},
    {id: "YG-001", nome: "Yami Yugi", nivel: 4, tipo: "action", atk: 2500, def: 2100, efeito: "Historia/Efeito: O melhor duelista de YU-GI-OH! quando Yugi Moto resolve o enigma do milênio ele invoca o espirito do farao! só que por ser um shonen ele sabe como usar o 'poder do protagonista' né :]/ ROUBE 100 LP do seu oponente para voce xdxd", imagem:"images/YUGI.jpg"}
    
    

];

// A tabela EFEITOS e as funções de efeito (efeitoDestruirCartaInimiga,
// efeitoNegarAtaqueInimigo) foram movidas para o index.js.
// Motivo: aqui em cards.js, essas funções ainda não existiam no momento
// em que este arquivo era executado (cards.js carrega ANTES de index.js),
// então referenciá-las aqui sempre vai gerar ReferenceError e travar
// a execução deste script no meio do arquivo.